import type { Movie } from './types';
export const INITIAL_MOVIES: Movie[] = [
  { id: '1', title: 'My Neighbor Totoro', year: 1988, status: 'active', votesNap: 150, votesEngaging: 5, tags: ['Calm', 'Nature', 'Ghibli'] },
  { id: '2', title: 'Fantasia', year: 1940, status: 'active', votesNap: 120, votesEngaging: 10, tags: ['Classical Music', 'Abstract', 'No Dialogue'] },
  { id: '3', title: '2001: A Space Odyssey', year: 1968, status: 'active', votesNap: 95, votesEngaging: 20, tags: ['Space', 'Slow Burn', 'Ambience'] },
  { id: '4', title: 'Lost in Translation', year: 2003, status: 'active', votesNap: 88, votesEngaging: 12, tags: ['Atmospheric', 'Neon', 'Melancholy'] },
  { id: '5', title: 'The Grand Budapest Hotel', year: 2014, status: 'active', votesNap: 72, votesEngaging: 15, tags: ['Symmetry', 'Colors', 'Comforting'] },
  { id: '6', title: 'Ponyo', year: 2008, status: 'active', votesNap: 65, votesEngaging: 4, tags: ['Water', 'Ghibli', 'Soothing'] },
  { id: '7', title: 'Blade Runner 2049', year: 2017, status: 'active', votesNap: 80, votesEngaging: 25, tags: ['Rain', 'Synth', 'Visuals'] },
  { id: '8', title: 'Kiki\'s Delivery Service', year: 1989, status: 'active', votesNap: 92, votesEngaging: 3, tags: ['Ghibli', 'European Town', 'Low Stress'] },
  { id: '9', title: 'Before Sunrise', year: 1995, status: 'active', votesNap: 58, votesEngaging: 18, tags: ['Walking', 'Dialogue', 'Soft Lighting'] },
  { id: '10', title: 'Nomadland', year: 2020, status: 'active', votesNap: 75, votesEngaging: 10, tags: ['Nature', 'Slow', 'Quiet'] },
  { id: '11', title: 'Microcosmos', year: 1996, status: 'active', votesNap: 110, votesEngaging: 2, tags: ['Nature', 'No Dialogue', 'Insects'] },
  { id: '12', title: 'The Red Turtle', year: 2016, status: 'active', votesNap: 85, votesEngaging: 5, tags: ['No Dialogue', 'Island', 'Sea'] },
  { id: '13', title: 'Baraka', year: 1992, status: 'active', votesNap: 130, votesEngaging: 1, tags: ['Visual Poem', 'World', 'No Dialogue'] },
  { id: '14', title: 'Columbus', year: 2017, status: 'active', votesNap: 55, votesEngaging: 8, tags: ['Architecture', 'Quiet', 'Stillness'] },
  { id: '15', title: 'Spring, Summer, Fall, Winter... and Spring', year: 2003, status: 'active', votesNap: 68, votesEngaging: 6, tags: ['Lake', 'Monastery', 'Slow'] },
  { id: '16', title: 'Paterson', year: 2016, status: 'active', votesNap: 62, votesEngaging: 9, tags: ['Poetry', 'Routine', 'Soft'] },
  { id: '17', title: 'Interstellar', year: 2014, status: 'active', votesNap: 70, votesEngaging: 45, tags: ['Space', 'Organ Music', 'Long'] },
  { id: '18', title: 'Secret World of Arrietty', year: 2010, status: 'active', votesNap: 78, votesEngaging: 4, tags: ['Ghibli', 'Tiny World', 'Rain'] },
  { id: '19', title: 'The Straight Story', year: 1999, status: 'active', votesNap: 52, votesEngaging: 7, tags: ['Road Movie', 'Tractor', 'Nature'] },
  { id: '20', title: 'Winged Migration', year: 2001, status: 'active', votesNap: 95, votesEngaging: 3, tags: ['Nature', 'Birds', 'Sky'] },
  { id: '21', title: 'Local Hero', year: 1983, status: 'active', votesNap: 48, votesEngaging: 5, tags: ['Coastal', 'Quirky', 'Starry Sky'] },
  { id: '22', title: 'Samsara', year: 2011, status: 'active', votesNap: 105, votesEngaging: 5, tags: ['Visual Poem', 'Epic', 'No Dialogue'] },
  { id: '23', title: 'Solaris', year: 1972, status: 'active', votesNap: 88, votesEngaging: 35, tags: ['Space', 'Psychological', 'Very Slow'] },
  { id: '24', title: 'Only Yesterday', year: 1991, status: 'active', votesNap: 66, votesEngaging: 4, tags: ['Ghibli', 'Memory', 'Countryside'] },
  { id: '25', title: 'O Brother, Where Art Thou?', year: 2000, status: 'active', votesNap: 50, votesEngaging: 15, tags: ['Folk Music', 'Sepia', 'Familiar'] },
  { id: '26', title: 'The Tree of Life', year: 2011, status: 'active', votesNap: 115, votesEngaging: 22, tags: ['Cosmic', 'Watercolor', 'Whispers'] },
  { id: '27', title: 'Embrace of the Serpent', year: 2015, status: 'active', votesNap: 82, votesEngaging: 10, tags: ['Amazon', 'Monochrome', 'Mystical'] },
  { id: '28', title: 'Koyaanisqatsi', year: 1982, status: 'active', votesNap: 145, votesEngaging: 8, tags: ['Philip Glass', 'Time-lapse', 'Ambient'] },
  { id: '29', title: 'Uncle Boonmee Who Can Recall His Past Lives', year: 2010, status: 'active', votesNap: 74, votesEngaging: 12, tags: ['Jungle', 'Liminal', 'Static'] },
  { id: '30', title: 'Planet Earth: Caves', year: 2006, status: 'active', votesNap: 160, votesEngaging: 2, tags: ['Nature', 'Attenborough', 'Echo'] },
  { id: '31', title: 'Stalker', year: 1979, status: 'active', votesNap: 98, votesEngaging: 30, tags: ['Philosophical', 'Rain', 'Slow Cinema'] },
  { id: '32', title: 'The Tale of the Princess Kaguya', year: 2013, status: 'active', votesNap: 89, votesEngaging: 7, tags: ['Watercolor', 'Folklore', 'Ghibli'] },
  { id: '33', title: 'March of the Penguins', year: 2005, status: 'active', votesNap: 112, votesEngaging: 4, tags: ['Ice', 'Wind', 'Narrated'] },
  { id: '34', title: 'Man with a Movie Camera', year: 1929, status: 'active', votesNap: 54, votesEngaging: 15, tags: ['Silent', 'Rhythmic', 'City'] },
  { id: '35', title: 'The Mirror', year: 1975, status: 'active', votesNap: 77, votesEngaging: 18, tags: ['Poetic', 'Dreamlike', 'Tarkovsky'] },
  { id: '36', title: 'Arrival', year: 2016, status: 'active', votesNap: 81, votesEngaging: 24, tags: ['Language', 'Fog', 'Low Frequency'] },
  { id: '37', title: 'Werckmeister Harmonies', year: 2000, status: 'active', votesNap: 45, votesEngaging: 10, tags: ['Long Takes', 'Piano', 'B&W'] },
  { id: '38', title: 'Portrait of a Lady on Fire', year: 2019, status: 'active', votesNap: 67, votesEngaging: 9, tags: ['Ocean', 'Painting', 'Static'] },
  { id: '39', title: 'Under the Skin', year: 2013, status: 'active', votesNap: 59, votesEngaging: 28, tags: ['Synthesizer', 'Abstract', 'Cold'] },
  { id: '40', title: 'Memoria', year: 2021, status: 'active', votesNap: 132, votesEngaging: 5, tags: ['Sonic', 'Stillness', 'Jungles'] },
  { id: '41', title: 'The Night of the Hunter', year: 1955, status: 'active', votesNap: 44, votesEngaging: 12, tags: ['Fairy Tale', 'River', 'Noir'] },
  { id: '42', title: 'Sunrise: A Song of Two Humans', year: 1927, status: 'active', votesNap: 51, votesEngaging: 6, tags: ['Silent', 'Orchestral', 'Classic'] },
  { id: '43', title: 'Encounters at the End of the World', year: 2007, status: 'active', votesNap: 72, votesEngaging: 8, tags: ['Antarctica', 'Herzog', 'Seal Sounds'] },
  { id: '44', title: 'When Marnie Was There', year: 2014, status: 'active', votesNap: 84, votesEngaging: 3, tags: ['Marsh', 'Ghibli', 'Quiet'] },
  { id: '45', title: 'The Assassination of Jesse James by the Coward Robert Ford', year: 2007, status: 'active', votesNap: 92, votesEngaging: 15, tags: ['Snow', 'Lyrical', 'Deakins'] },
  { id: '46', title: 'Cemetery of Splendour', year: 2015, status: 'active', votesNap: 118, votesEngaging: 4, tags: ['Hospital', 'Lights', 'Hypnotic'] },
  { id: '47', title: 'Mon Oncle', year: 1958, status: 'active', votesNap: 49, votesEngaging: 11, tags: ['French', 'Whimsical', 'Low Dialogue'] },
  { id: '48', title: 'Atanarjuat: The Fast Runner', year: 2001, status: 'active', votesNap: 63, votesEngaging: 5, tags: ['Arctic', 'Inuit', 'Vast'] },
  { id: '49', title: 'Le Quattro Volte', year: 2010, status: 'active', votesNap: 88, votesEngaging: 2, tags: ['Goats', 'Village', 'Silent'] },
  { id: '50', title: 'Jiro Dreams of Sushi', year: 2011, status: 'active', votesNap: 71, votesEngaging: 14, tags: ['Routine', 'Minimalist', 'Jazz'] }
];
export const MOCK_USERS = [];
export const MOCK_CHATS = [];
export const MOCK_CHAT_MESSAGES = [];