import type { Movie } from './types';
const defaultTags = ['Familiar', 'Comfort Rewatch', 'Low Stress'];
const baseVotes = { votesNap: 15, votesEngaging: 3 };
export const INITIAL_MOVIES: Movie[] = [
  { id: '1', title: 'Harry Potter (Complete Film Series)', year: 2001, status: 'active', ...baseVotes, tags: [...defaultTags, 'Magic'] },
  { id: '2', title: 'The Lord of the Rings (Extended Editions Trilogy)', year: 2001, status: 'active', ...baseVotes, tags: [...defaultTags, 'Epic'] },
  { id: '3', title: 'The Hobbit (Complete Trilogy)', year: 2012, status: 'active', ...baseVotes, tags: [...defaultTags, 'Fantasy'] },
  { id: '4', title: 'Tron: Legacy', year: 2010, status: 'active', ...baseVotes, tags: [...defaultTags, 'Synth', 'Neon'] },
  { id: '5', title: 'Blade Runner (Final Cut)', year: 1982, status: 'active', ...baseVotes, tags: [...defaultTags, 'Atmospheric'] },
  { id: '6', title: 'Blade Runner 2049', year: 2017, status: 'active', ...baseVotes, tags: [...defaultTags, 'Rain', 'Visuals'] },
  { id: '7', title: 'Arrival', year: 2016, status: 'active', ...baseVotes, tags: [...defaultTags, 'Quiet', 'Fog'] },
  { id: '8', title: 'Interstellar', year: 2014, status: 'active', ...baseVotes, tags: [...defaultTags, 'Space', 'Organ Music'] },
  { id: '9', title: 'Wind River', year: 2017, status: 'active', ...baseVotes, tags: [...defaultTags, 'Snow', 'Quiet'] },
  { id: '10', title: 'Ad Astra', year: 2019, status: 'active', ...baseVotes, tags: [...defaultTags, 'Space', 'Slow'] },
  { id: '11', title: 'Moon', year: 2009, status: 'active', ...baseVotes, tags: [...defaultTags, 'Isolation', 'Ambient'] },
  { id: '12', title: 'Solaris (2002)', year: 2002, status: 'active', ...baseVotes, tags: [...defaultTags, 'Space', 'Dreamlike'] },
  { id: '13', title: 'Oblivion', year: 2013, status: 'active', ...baseVotes, tags: [...defaultTags, 'Clean Aesthetic', 'Synth'] },
  { id: '14', title: 'A Ghost Story', year: 2017, status: 'active', ...baseVotes, tags: [...defaultTags, 'Stillness', 'Slow'] },
  { id: '15', title: 'The Assassination of Jesse James by the Coward Robert Ford', year: 2007, status: 'active', ...baseVotes, tags: [...defaultTags, 'Lyrical', 'Snow'] },
  { id: '16', title: 'No Country for Old Men', year: 2007, status: 'active', ...baseVotes, tags: [...defaultTags, 'Minimalist', 'No Music'] },
  { id: '17', title: 'Margin Call', year: 2011, status: 'active', ...baseVotes, tags: [...defaultTags, 'Dialogue', 'Night'] },
  { id: '18', title: 'Tinker Tailor Soldier Spy', year: 2011, status: 'active', ...baseVotes, tags: [...defaultTags, 'Muted Colors', 'Slow'] },
  { id: '19', title: 'The Tree of Life', year: 2011, status: 'active', ...baseVotes, tags: [...defaultTags, 'Cosmic', 'Whispers'] },
  { id: '20', title: 'Her', year: 2013, status: 'active', ...baseVotes, tags: [...defaultTags, 'Soft Colors', 'Melancholy'] },
  { id: '21', title: 'Michael Clayton', year: 2007, status: 'active', ...baseVotes, tags: [...defaultTags, 'Rain', 'Dialogue'] },
  { id: '22', title: 'Zodiac', year: 2007, status: 'active', ...baseVotes, tags: [...defaultTags, 'Procedural', 'Rain'] },
  { id: '23', title: 'Lost in Translation', year: 2003, status: 'active', ...baseVotes, tags: [...defaultTags, 'Neon', 'Atmospheric'] },
  { id: '24', title: 'Moneyball', year: 2011, status: 'active', ...baseVotes, tags: [...defaultTags, 'Routine', 'Dialogue'] },
  { id: '25', title: 'The Shawshank Redemption', year: 1994, status: 'active', ...baseVotes, tags: [...defaultTags, 'Classic', 'Comforting'] },
  { id: '26', title: 'The Curious Case of Benjamin Button', year: 2008, status: 'active', ...baseVotes, tags: [...defaultTags, 'Epic', 'Storytelling'] },
  { id: '27', title: 'Hell or High Water', year: 2016, status: 'active', ...baseVotes, tags: [...defaultTags, 'Plains', 'Slow Burn'] },
  { id: '28', title: 'Sicario', year: 2015, status: 'active', ...baseVotes, tags: [...defaultTags, 'Desert', 'Drone'] },
  { id: '29', title: 'Prisoners', year: 2013, status: 'active', ...baseVotes, tags: [...defaultTags, 'Rain', 'Dark'] },
  { id: '30', title: 'The Conversation', year: 1974, status: 'active', ...baseVotes, tags: [...defaultTags, 'Lo-fi', 'Rain'] },
  { id: '31', title: 'Dances with Wolves', year: 1990, status: 'active', ...baseVotes, tags: [...defaultTags, 'Nature', 'Quiet'] },
  { id: '32', title: 'The Last Samurai', year: 2003, status: 'active', ...baseVotes, tags: [...defaultTags, 'Autumn', 'Nature'] },
  { id: '33', title: 'Kingdom of Heaven (Director’s Cut)', year: 2005, status: 'active', ...baseVotes, tags: [...defaultTags, 'Epic', 'Atmospheric'] },
  { id: '34', title: 'Lawrence of Arabia', year: 1962, status: 'active', ...baseVotes, tags: [...defaultTags, 'Desert', 'Vast'] },
  { id: '35', title: 'Out of Africa', year: 1985, status: 'active', ...baseVotes, tags: [...defaultTags, 'Nature', 'Lyrical'] },
  { id: '36', title: 'A River Runs Through It', year: 1992, status: 'active', ...baseVotes, tags: [...defaultTags, 'Water', 'Nature'] },
  { id: '37', title: 'The English Patient', year: 1996, status: 'active', ...baseVotes, tags: [...defaultTags, 'Sand', 'Slow'] },
  { id: '38', title: 'Columbus', year: 2017, status: 'active', ...baseVotes, tags: [...defaultTags, 'Architecture', 'Stillness'] },
  { id: '39', title: 'Paterson', year: 2016, status: 'active', ...baseVotes, tags: [...defaultTags, 'Poetry', 'Routine'] },
  { id: '40', title: 'The Straight Story', year: 1999, status: 'active', ...baseVotes, tags: [...defaultTags, 'Countryside', 'Slow'] },
  { id: '41', title: 'Drive', year: 2011, status: 'active', ...baseVotes, tags: [...defaultTags, 'Neon', 'Synth'] },
  { id: '42', title: 'The Grey', year: 2011, status: 'active', ...baseVotes, tags: [...defaultTags, 'Snow', 'Wind'] },
  { id: '43', title: 'The Social Network', year: 2010, status: 'active', ...baseVotes, tags: [...defaultTags, 'Fast Dialogue', 'Rain'] },
  { id: '44', title: 'Fantastic Beasts and Where to Find Them', year: 2016, status: 'active', ...baseVotes, tags: [...defaultTags, 'Magic', 'Whimsical'] },
  { id: '45', title: 'WALL·E', year: 2008, status: 'active', ...baseVotes, tags: [...defaultTags, 'No Dialogue', 'Space'] },
  { id: '46', title: 'All Is Lost', year: 2013, status: 'active', ...baseVotes, tags: [...defaultTags, 'Sea', 'No Dialogue'] },
  { id: '47', title: 'Before Sunrise', year: 1995, status: 'active', ...baseVotes, tags: [...defaultTags, 'Walking', 'Dialogue'] },
  { id: '48', title: 'Before Sunset', year: 2004, status: 'active', ...baseVotes, tags: [...defaultTags, 'Walking', 'Golden Hour'] },
  { id: '49', title: 'The Grand Budapest Hotel', year: 2014, status: 'active', ...baseVotes, tags: [...defaultTags, 'Symmetry', 'Comforting'] },
  { id: '50', title: 'Finding Nemo', year: 2003, status: 'active', ...baseVotes, tags: [...defaultTags, 'Underwater', 'Classic'] },
];
export const MOCK_USERS = [];
export const MOCK_CHATS = [];
export const MOCK_CHAT_MESSAGES = [];